format="$cmd_duration$custom$directory$git_branch$git_state$character"
add_newline = false

[git_state]
format = "[|$state]($style)"
style = "dimmed"

[git_branch]
symbol = "î‚ "
format = "[ $symbol$branch ]($style)"
style = "dimmed"

[directory]
format = "[$path]($style)"
truncate_to_repo = false
truncation_length = 5
truncation_symbol="â€¦/"
style = "dimmed"

# [directory.substitutions]
# "~" = "ğŸ "
# "Documents" = "ğŸ“„"
# "doc" = "ğŸ“„"
# "bin" = "âš™"
# "src" = "ïª¿"
# "dot.config" = "ïª¶"
# ".config" = "ïª¶"
# ".dotfile" = "ğŸ›  "
# "home" = "ğŸ˜ "
# "figs" = "ï‡… "
# "Downloads" = "ğŸ“¥"
# "Music" = "ğŸœ"
# "Pictures" = "ğŸ“·"
# "Video" = "ï€½ "
# "Calibre" = "ğŸ“š"
# "android" = "îœ "
# "Android" = "îœ "
# "cs6" = "ï¦©"
# "lectures" = "ã‰†"
# "clash" = "ï¨€"
# "Mail" = "ğŸ“§"
# "public_html" = "ïª‡"
# "linux" = "ï…¼ "

#ğŸ–§
[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

# Show duration for commands that took more than 3s only
[cmd_duration]
format = "[ğŸ”ƒ$duration]($style) "
min_time = 3000
show_milliseconds = false
style = "dimmed"

# Using a custom format to highlight current non-system python in a compact manner
# - ğŸ: python from virtual env is active
# - ğŸ¦: python from pyenv is active
# [custom.py]
# command = """ pv=$(python --version | grep -Eo "\\d+\\.\\d+"); if [ -n "$VIRTUAL_ENV" ]; then echo "ğŸ $pv"; else echo "ğŸ¦ $pv"; fi """
# format = "[$output]($style) "
# style = "blue"
# when = """ test -n "$VIRTUAL_ENV" || echo $PATH | grep /pyenv/ """
